"""Static publication checks for the integrated engineering report."""

from __future__ import annotations

import re
import unittest
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
REPORT_PATH = PROJECT_ROOT / "docs" / "PROJECT_REPORT.md"


class ProjectReportDocumentTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.text = REPORT_PATH.read_text(encoding="utf-8")
        cls.normalized_text = " ".join(cls.text.split())

    def test_report_has_the_expected_visual_contract(self):
        image_targets = re.findall(r"!\[[^\]]*\]\(([^)]+)\)", self.text)
        table_captions = re.findall(r"^\*\*Table \d+\.", self.text, flags=re.MULTILINE)
        figure_captions = re.findall(r"^\*\*Figure \d+\.", self.text, flags=re.MULTILINE)
        interpretations = re.findall(r"^\*\*Interpretation\.\*\*", self.text, flags=re.MULTILINE)

        self.assertEqual(len(image_targets), 6)
        self.assertEqual(len(figure_captions), 6)
        self.assertEqual(len(table_captions), 5)
        self.assertEqual(len(interpretations), 11)
        for target in image_targets:
            self.assertTrue((REPORT_PATH.parent / target).is_file(), target)

    def test_each_visual_is_followed_immediately_by_its_interpretation(self):
        lines = self.text.splitlines()
        figure_numbers = []
        table_numbers = []

        def next_nonblank(index):
            while index < len(lines) and not lines[index].strip():
                index += 1
            return index

        for index, line in enumerate(lines):
            figure_match = re.match(r"\*\*Figure (\d+)\.", line)
            table_match = re.match(r"\*\*Table (\d+)\.", line)
            if figure_match:
                figure_numbers.append(int(figure_match.group(1)))
                content_index = next_nonblank(index + 1)
                self.assertRegex(lines[content_index], r"^!\[[^\]]*\]\([^)]+\)$")
                interpretation_index = next_nonblank(content_index + 1)
                self.assertTrue(
                    lines[interpretation_index].startswith("**Interpretation.**"),
                    f"Figure {figure_match.group(1)} lacks an immediate interpretation.",
                )
            elif table_match:
                table_numbers.append(int(table_match.group(1)))
                content_index = next_nonblank(index + 1)
                self.assertTrue(lines[content_index].startswith("|"))
                while content_index < len(lines) and lines[content_index].startswith("|"):
                    content_index += 1
                interpretation_index = next_nonblank(content_index)
                self.assertTrue(
                    lines[interpretation_index].startswith("**Interpretation.**"),
                    f"Table {table_match.group(1)} lacks an immediate interpretation.",
                )

        self.assertEqual(figure_numbers, list(range(1, 7)))
        self.assertEqual(table_numbers, list(range(1, 6)))

    def test_report_preserves_verified_claim_boundaries(self):
        required = (
            "0.546805",
            "0.579597",
            "0.032792",
            "0.070629",
            "9,525",
            "36,721",
            "5,000",
            "19,196",
            "0.401573",
            "7,727",
            "1,677",
            "4,193",
            "not claims of independent generalization",
            "low-floor 101-point AP50",
            "threshold-constrained 11-point AP50",
            "not directly comparable",
        )
        for phrase in required:
            self.assertIn(phrase, self.normalized_text)

        prohibited = (
            "coursework",
            "github classroom",
            "class assignment",
            "rebuilt",
            "reference implementation",
            "generated by ai",
            "```mermaid",
        )
        lowered = self.text.lower()
        for phrase in prohibited:
            self.assertNotIn(phrase, lowered)


if __name__ == "__main__":
    unittest.main()
